# Site settings
title: Micro Talk
email: contact@micro-talk.studio
url: https://micro-talk.studio
description: "Composer duo from Amsterdam"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
cover:
  url: '/img/Micro-Talk-42x42-cm.jpg'

# Build settings
markdown: kramdown
permalink: pretty
